eprx-elasticsearch:
  container_name: eprx-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/eprx/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
eprx-postgresql:
  container_name: eprx-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/eprx/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=eprx
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
